version: '3.2'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile.dev
        ports:
            - ${NGINX_PORT}:80 # expose ports - HOST:CONTAINER
        volumes:
            - ./api/apidocs:/usr/share/nginx/apidocs
        links:
            - app
            - api
    api:
        build: ./api
        volumes:
            - ./api/:/srv/api
            - /srv/api/node_modules
        ports:
            - ${API_PORT}:3000 # expose ports - HOST:CONTAINER
        environment:
            - API_PORT=${API_PORT}
            - DEBUG=${DEBUG}
            - NODE_ENV=${NODE_ENV}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_NAME=${MONGO_NAME}
            - BASE_URL=${BASE_URL}
    app:
        build: ./app
        volumes:
            - ./app/:/srv/app
            - /srv/app/node_modules
        expose:
            - "3000"
        # ports:
        #     - 35729:35729 # expose ports - HOST:CONTAINER
        depends_on:
            - api
    mongo:
        image: mongo:latest
        volumes:
            - ./data/db/:/data/db
        ports:
            - ${MONGO_PORT}:27017 # expose ports - HOST:CONTAINER
