version: '3.2'
services:
  web:
    build: ./web/
    ports:
      - ${NGINX_PORT}:80 # expose ports - HOST:CONTAINER
    volumes:
      - ./app/build/:/usr/share/nginx/html
    environment:
      - API_PORT=${API_PORT}
    links:
      - api
  api:
    build: ./api/
    volumes:
      - ./api/:/srv/api
      - /srv/api/node_modules
    ports:
      - ${API_PORT}:3000 # expose ports - HOST:CONTAINER
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - ./data/db/:/data/db
    ports:
      - ${MONGO_PORT}:27017 # expose ports - HOST:CONTAINER
